services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-server
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    command: ["--verbose"]
